name: caching the node app
on: [workflow_dispatch]
jobs:
    node-app-job:
        runs-on: ubuntu-latest
        steps:
            
            - uses: actions/checkout@v4
            - name: cahce the node module
              id: cache-dep
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: "npm-cache-key"
            - name: Display cache output
              run: echo '${{toJson(steps.cache-dep.outputs)}}'   
            - name: install depe
              run: npm install
            - name: Use Axios
              uses: actions/github-script@v6
              with:
                script: |
                  const axios = require('axios');
                  const res = await axios('https://icanhazdadjoke.com/', { headers: { Accept: 'text/plain' } })
                  console.log(res.data)
        
